title: Abdulwaheed Tella
logo: asset/My Passport Photograph.jpg
description: Data Analyst | Geospatial Analyst | Environmental Scientist | Researcher
show_downloads: false
theme: jekyll-theme-minimal
